modLoader="javafml"
loaderVersion="[40,)"
license="GPL-3.0-only"

[[mods]]
modId="better_selective_combat"
version="${version}"
displayName="Better Selective Combat"
displayTest="IGNORE_ALL_VERSION"
authors="wechirok"
logoFile="icon.png"
description='''Pick which weapons should ignore Better Combat on the client and server side.'''

[[dependencies.better_selective_combat]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_range}"
ordering="NONE"
side="BOTH"

[[dependencies.better_selective_combat]]
modId="bettercombat"
mandatory=true
versionRange="${better_combat_range}"
ordering="AFTER"
side="BOTH"

[[dependencies.better_selective_combat]]
modId="luckperms"
mandatory=false
versionRange="[5,)"
ordering="AFTER"
side="BOTH"
